// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.DocumentReference;

privileged aspect DocumentReference_Roo_JavaBean {
    
    public String DocumentReference.getName() {
        return this.name;
    }
    
    public void DocumentReference.setName(String name) {
        this.name = name;
    }
    
}
