// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.FinanceResource;

privileged aspect FinanceResource_Roo_JavaBean {
    
    public String FinanceResource.getType() {
        return this.type;
    }
    
    public void FinanceResource.setType(String type) {
        this.type = type;
    }
    
}
