// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.FinanceResource;
import javax.persistence.Entity;

privileged aspect FinanceResource_Roo_Jpa_Entity {
    
    declare @type: FinanceResource: @Entity;
    
}
