// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.Activity;
import ch.lan.teko.model.ActivityDataOnDemand;
import ch.lan.teko.model.Employee;
import ch.lan.teko.model.EmployeeDataOnDemand;
import java.time.LocalDate;
import org.springframework.beans.factory.annotation.Autowired;

privileged aspect ActivityDataOnDemand_Roo_DataOnDemand {
    
    @Autowired
    EmployeeDataOnDemand ActivityDataOnDemand.employeeDataOnDemand;
    
    public void ActivityDataOnDemand.setEndDate(Activity obj, int index) {
        LocalDate endDate = null;
        obj.setEndDate(endDate);
    }
    
    public void ActivityDataOnDemand.setPlanedEndDate(Activity obj, int index) {
        LocalDate planedEndDate = null;
        obj.setPlanedEndDate(planedEndDate);
    }
    
    public void ActivityDataOnDemand.setPlanedStartDate(Activity obj, int index) {
        LocalDate planedStartDate = null;
        obj.setPlanedStartDate(planedStartDate);
    }
    
    public void ActivityDataOnDemand.setProgress(Activity obj, int index) {
        Byte progress = new Byte("1");
        obj.setProgress(progress);
    }
    
    public void ActivityDataOnDemand.setResponsible(Activity obj, int index) {
        Employee responsible = employeeDataOnDemand.getRandomEmployee();
        obj.setResponsible(responsible);
    }
    
    public void ActivityDataOnDemand.setStartDate(Activity obj, int index) {
        LocalDate startDate = null;
        obj.setStartDate(startDate);
    }
    
}
