// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.DocumentReference;
import ch.lan.teko.model.DocumentReferenceDataOnDemand;

privileged aspect DocumentReferenceDataOnDemand_Roo_DataOnDemand {
    
    public void DocumentReferenceDataOnDemand.setName(DocumentReference obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void DocumentReferenceDataOnDemand.setPath(DocumentReference obj, int index) {
        String path = "path_" + index;
        obj.setPath(path);
    }
    
}
