// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.DocumentReference;
import ch.lan.teko.model.DocumentReferenceDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DocumentReferenceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DocumentReferenceDataOnDemand: @Component;
    
    private Random DocumentReferenceDataOnDemand.rnd = new SecureRandom();
    
    private List<DocumentReference> DocumentReferenceDataOnDemand.data;
    
    public DocumentReference DocumentReferenceDataOnDemand.getNewTransientDocumentReference(int index) {
        DocumentReference obj = new DocumentReference();
        setName(obj, index);
        return obj;
    }
    
    public void DocumentReferenceDataOnDemand.setName(DocumentReference obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public DocumentReference DocumentReferenceDataOnDemand.getSpecificDocumentReference(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        DocumentReference obj = data.get(index);
        Long id = obj.getId();
        return DocumentReference.findDocumentReference(id);
    }
    
    public DocumentReference DocumentReferenceDataOnDemand.getRandomDocumentReference() {
        init();
        DocumentReference obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return DocumentReference.findDocumentReference(id);
    }
    
    public boolean DocumentReferenceDataOnDemand.modifyDocumentReference(DocumentReference obj) {
        return false;
    }
    
    public void DocumentReferenceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = DocumentReference.findDocumentReferenceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'DocumentReference' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<DocumentReference>();
        for (int i = 0; i < 10; i++) {
            DocumentReference obj = getNewTransientDocumentReference(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
