// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.Employee;
import ch.lan.teko.model.EmployeeDataOnDemand;

privileged aspect EmployeeDataOnDemand_Roo_DataOnDemand {
    
    public void EmployeeDataOnDemand.setJob(Employee obj, int index) {
        String job = "job_" + index;
        obj.setJob(job);
    }
    
    public void EmployeeDataOnDemand.setName(Employee obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void EmployeeDataOnDemand.setPensum(Employee obj, int index) {
        Byte pensum = new Byte("1");
        obj.setPensum(pensum);
    }
    
    public void EmployeeDataOnDemand.setSurname(Employee obj, int index) {
        String surname = "surname_" + index;
        obj.setSurname(surname);
    }
    
}
