// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.FinanceResource;
import ch.lan.teko.model.FinanceResourceDataOnDemand;

privileged aspect FinanceResourceDataOnDemand_Roo_DataOnDemand {
    
    public void FinanceResourceDataOnDemand.setEffectiv(FinanceResource obj, int index) {
        Integer effectiv = new Integer(index);
        obj.setEffectiv(effectiv);
    }
    
    public void FinanceResourceDataOnDemand.setExplanation(FinanceResource obj, int index) {
        String explanation = "explanation_" + index;
        obj.setExplanation(explanation);
    }
    
    public void FinanceResourceDataOnDemand.setPlaned(FinanceResource obj, int index) {
        Integer planed = new Integer(index);
        obj.setPlaned(planed);
    }
    
    public void FinanceResourceDataOnDemand.setType(FinanceResource obj, int index) {
        String type = "type_" + index;
        obj.setType(type);
    }
    
}
