// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.Milestone;
import ch.lan.teko.model.MilestoneDataOnDemand;
import java.time.LocalDate;

privileged aspect MilestoneDataOnDemand_Roo_DataOnDemand {
    
    public void MilestoneDataOnDemand.setName(Milestone obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void MilestoneDataOnDemand.setPlanedDate(Milestone obj, int index) {
        LocalDate planedDate = null;
        obj.setPlanedDate(planedDate);
    }
    
}
