// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.MilestoneIntegrationTest;
import ch.lan.teko.service.MilestoneService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;

privileged aspect MilestoneIntegrationTest_Roo_IntegrationTest {
    
    @Autowired
    MilestoneService MilestoneIntegrationTest.milestoneService;
    
    @Test
    public void MilestoneIntegrationTest.testCountAllMilestones() {
        Assert.assertNotNull("Data on demand for 'Milestone' failed to initialize correctly", dod.getRandomMilestone());
        long count = milestoneService.countAllMilestones();
        Assert.assertTrue("Counter for 'Milestone' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MilestoneIntegrationTest.testFindMilestone() {
        Milestone obj = dod.getRandomMilestone();
        Assert.assertNotNull("Data on demand for 'Milestone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Milestone' failed to provide an identifier", id);
        obj = milestoneService.findMilestone(id);
        Assert.assertNotNull("Find method for 'Milestone' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Milestone' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MilestoneIntegrationTest.testFindAllMilestones() {
        Assert.assertNotNull("Data on demand for 'Milestone' failed to initialize correctly", dod.getRandomMilestone());
        long count = milestoneService.countAllMilestones();
        Assert.assertTrue("Too expensive to perform a find all test for 'Milestone', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Milestone> result = milestoneService.findAllMilestones();
        Assert.assertNotNull("Find all method for 'Milestone' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Milestone' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MilestoneIntegrationTest.testFindMilestoneEntries() {
        Assert.assertNotNull("Data on demand for 'Milestone' failed to initialize correctly", dod.getRandomMilestone());
        long count = milestoneService.countAllMilestones();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Milestone> result = milestoneService.findMilestoneEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Milestone' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Milestone' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MilestoneIntegrationTest.testUpdateMilestoneUpdate() {
        Milestone obj = dod.getRandomMilestone();
        Assert.assertNotNull("Data on demand for 'Milestone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Milestone' failed to provide an identifier", id);
        obj = milestoneService.findMilestone(id);
        boolean modified =  dod.modifyMilestone(obj);
        Integer currentVersion = obj.getVersion();
        Milestone merged = milestoneService.updateMilestone(obj);
        milestoneRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Milestone' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MilestoneIntegrationTest.testSaveMilestone() {
        Assert.assertNotNull("Data on demand for 'Milestone' failed to initialize correctly", dod.getRandomMilestone());
        Milestone obj = dod.getNewTransientMilestone(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Milestone' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Milestone' identifier to be null", obj.getId());
        try {
            milestoneService.saveMilestone(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        milestoneRepository.flush();
        Assert.assertNotNull("Expected 'Milestone' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MilestoneIntegrationTest.testDeleteMilestone() {
        Milestone obj = dod.getRandomMilestone();
        Assert.assertNotNull("Data on demand for 'Milestone' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Milestone' failed to provide an identifier", id);
        obj = milestoneService.findMilestone(id);
        milestoneService.deleteMilestone(obj);
        milestoneRepository.flush();
        Assert.assertNull("Failed to remove 'Milestone' with identifier '" + id + "'", milestoneService.findMilestone(id));
    }
    
}
