// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.Employee;
import ch.lan.teko.model.EmployeeDataOnDemand;
import ch.lan.teko.model.PersonalResource;
import ch.lan.teko.model.PersonalResourceDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;

privileged aspect PersonalResourceDataOnDemand_Roo_DataOnDemand {
    
    @Autowired
    EmployeeDataOnDemand PersonalResourceDataOnDemand.employeeDataOnDemand;
    
    public void PersonalResourceDataOnDemand.setEffectiv(PersonalResource obj, int index) {
        Integer effectiv = new Integer(index);
        obj.setEffectiv(effectiv);
    }
    
    public void PersonalResourceDataOnDemand.setEmployee(PersonalResource obj, int index) {
        Employee employee = employeeDataOnDemand.getRandomEmployee();
        obj.setEmployee(employee);
    }
    
    public void PersonalResourceDataOnDemand.setExplanation(PersonalResource obj, int index) {
        String explanation = "explanation_" + index;
        obj.setExplanation(explanation);
    }
    
    public void PersonalResourceDataOnDemand.setJob(PersonalResource obj, int index) {
        String job = "job_" + index;
        obj.setJob(job);
    }
    
    public void PersonalResourceDataOnDemand.setPlaned(PersonalResource obj, int index) {
        Integer planed = new Integer(index);
        obj.setPlaned(planed);
    }
    
}
