// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.Phase;
import ch.lan.teko.model.PhaseDataOnDemand;
import java.time.LocalDate;

privileged aspect PhaseDataOnDemand_Roo_DataOnDemand {
    
    public void PhaseDataOnDemand.setApprovalDate(Phase obj, int index) {
        LocalDate approvalDate = null;
        obj.setApprovalDate(approvalDate);
    }
    
    public void PhaseDataOnDemand.setPhaseState(Phase obj, int index) {
        String phaseState = "phaseState_" + index;
        obj.setPhaseState(phaseState);
    }
    
    public void PhaseDataOnDemand.setPlanedReviewDate(Phase obj, int index) {
        LocalDate planedReviewDate = null;
        obj.setPlanedReviewDate(planedReviewDate);
    }
    
    public void PhaseDataOnDemand.setProgress(Phase obj, int index) {
        Byte progress = new Byte("1");
        obj.setProgress(progress);
    }
    
    public void PhaseDataOnDemand.setReviewDate(Phase obj, int index) {
        LocalDate reviewDate = null;
        obj.setReviewDate(reviewDate);
    }
    
}
