// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.Phase;
import ch.lan.teko.model.PhaseDataOnDemand;
import ch.lan.teko.model.PhaseIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PhaseIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PhaseIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PhaseIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PhaseIntegrationTest: @Transactional;
    
    @Autowired
    PhaseDataOnDemand PhaseIntegrationTest.dod;
    
    @Test
    public void PhaseIntegrationTest.testCountPhases() {
        Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", dod.getRandomPhase());
        long count = Phase.countPhases();
        Assert.assertTrue("Counter for 'Phase' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PhaseIntegrationTest.testFindPhase() {
        Phase obj = dod.getRandomPhase();
        Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phase' failed to provide an identifier", id);
        obj = Phase.findPhase(id);
        Assert.assertNotNull("Find method for 'Phase' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Phase' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PhaseIntegrationTest.testFindAllPhases() {
        Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", dod.getRandomPhase());
        long count = Phase.countPhases();
        Assert.assertTrue("Too expensive to perform a find all test for 'Phase', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Phase> result = Phase.findAllPhases();
        Assert.assertNotNull("Find all method for 'Phase' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Phase' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PhaseIntegrationTest.testFindPhaseEntries() {
        Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", dod.getRandomPhase());
        long count = Phase.countPhases();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Phase> result = Phase.findPhaseEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Phase' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Phase' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PhaseIntegrationTest.testFlush() {
        Phase obj = dod.getRandomPhase();
        Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phase' failed to provide an identifier", id);
        obj = Phase.findPhase(id);
        Assert.assertNotNull("Find method for 'Phase' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPhase(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Phase' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhaseIntegrationTest.testMergeUpdate() {
        Phase obj = dod.getRandomPhase();
        Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phase' failed to provide an identifier", id);
        obj = Phase.findPhase(id);
        boolean modified =  dod.modifyPhase(obj);
        Integer currentVersion = obj.getVersion();
        Phase merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Phase' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhaseIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", dod.getRandomPhase());
        Phase obj = dod.getNewTransientPhase(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Phase' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Phase' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Phase' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PhaseIntegrationTest.testRemove() {
        Phase obj = dod.getRandomPhase();
        Assert.assertNotNull("Data on demand for 'Phase' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phase' failed to provide an identifier", id);
        obj = Phase.findPhase(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Phase' with identifier '" + id + "'", Phase.findPhase(id));
    }
    
}
