// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.ProcessModel;
import ch.lan.teko.model.ProcessModelDataOnDemand;

privileged aspect ProcessModelDataOnDemand_Roo_DataOnDemand {
    
    public void ProcessModelDataOnDemand.setName(ProcessModel obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ProcessModelDataOnDemand.setPhases(ProcessModel obj, int index) {
        String phases = "phases_" + index;
        obj.setPhases(phases);
    }
    
}
