// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.Employee;
import ch.lan.teko.model.EmployeeDataOnDemand;
import ch.lan.teko.model.ProcessModel;
import ch.lan.teko.model.ProcessModelDataOnDemand;
import ch.lan.teko.model.Project;
import ch.lan.teko.model.ProjectDataOnDemand;
import java.time.LocalDate;
import org.springframework.beans.factory.annotation.Autowired;

privileged aspect ProjectDataOnDemand_Roo_DataOnDemand {
    
    @Autowired
    ProcessModelDataOnDemand ProjectDataOnDemand.processModelDataOnDemand;
    
    @Autowired
    EmployeeDataOnDemand ProjectDataOnDemand.employeeDataOnDemand;
    
    public void ProjectDataOnDemand.setApprovalDate(Project obj, int index) {
        LocalDate approvalDate = null;
        obj.setApprovalDate(approvalDate);
    }
    
    public void ProjectDataOnDemand.setDescription(Project obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void ProjectDataOnDemand.setName(Project obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ProjectDataOnDemand.setPriority(Project obj, int index) {
        Byte priority = new Byte("1");
        obj.setPriority(priority);
    }
    
    public void ProjectDataOnDemand.setProcessModel(Project obj, int index) {
        ProcessModel processModel = processModelDataOnDemand.getRandomProcessModel();
        obj.setProcessModel(processModel);
    }
    
    public void ProjectDataOnDemand.setProgress(Project obj, int index) {
        Byte progress = new Byte("1");
        obj.setProgress(progress);
    }
    
    public void ProjectDataOnDemand.setProjectState(Project obj, int index) {
        String projectState = "projectState_" + index;
        obj.setProjectState(projectState);
    }
    
    public void ProjectDataOnDemand.setProjectmanager(Project obj, int index) {
        Employee projectmanager = employeeDataOnDemand.getRandomEmployee();
        obj.setProjectmanager(projectmanager);
    }
    
}
