// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ch.lan.teko.model;

import ch.lan.teko.model.Resource;
import ch.lan.teko.model.ResourceDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ResourceDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ResourceDataOnDemand: @Component;
    
    private Random ResourceDataOnDemand.rnd = new SecureRandom();
    
    private List<Resource> ResourceDataOnDemand.data;
    
    public Resource ResourceDataOnDemand.getNewTransientResource(int index) {
        Resource obj = new Resource();
        setEffectiv(obj, index);
        setExplanation(obj, index);
        setPlaned(obj, index);
        return obj;
    }
    
    public void ResourceDataOnDemand.setEffectiv(Resource obj, int index) {
        Integer effectiv = new Integer(index);
        obj.setEffectiv(effectiv);
    }
    
    public void ResourceDataOnDemand.setExplanation(Resource obj, int index) {
        String explanation = "explanation_" + index;
        obj.setExplanation(explanation);
    }
    
    public void ResourceDataOnDemand.setPlaned(Resource obj, int index) {
        Integer planed = new Integer(index);
        obj.setPlaned(planed);
    }
    
    public Resource ResourceDataOnDemand.getSpecificResource(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Resource obj = data.get(index);
        Long id = obj.getId();
        return Resource.findResource(id);
    }
    
    public Resource ResourceDataOnDemand.getRandomResource() {
        init();
        Resource obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Resource.findResource(id);
    }
    
    public boolean ResourceDataOnDemand.modifyResource(Resource obj) {
        return false;
    }
    
    public void ResourceDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Resource.findResourceEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Resource' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Resource>();
        for (int i = 0; i < 10; i++) {
            Resource obj = getNewTransientResource(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
